### PR TITLE
LiveUpdatePage: fix extra_stylesheets

### PR DESCRIPTION
**Pull request by bsimpson63**
:eyeglasses: @madbook @spladug

### CODE REVIEW

**Review by spladug — CHANGES_REQUESTED** [review]
can you explain what this fixes in the commit message please?

**Comment by bsimpson63** [comment]
💇

**Review by madbook — APPROVED** [review]

**Comment by bsimpson63** [comment]
I could also fix this by checking whether `extra_stylesheets` was passed into `Reddit.__init__` and if not use `Reddit.extra_stylesheets` instead of empty list.

**Review by spladug — APPROVED** [review]

**Comment by bsimpson63** [comment]
closed in favor of https://github.com/reddit/reddit-public/pull/6528

**Pull request closed without merging**
