### PR TITLE
Add /api/live/happening_now api

### PR DESCRIPTION
**Pull request by dkasper**
This will allow us to show a banner for the currently featured live event from mobile or other places that use the api

### CODE REVIEW

**Comment by dkasper** [comment]
👓 @umbrae @spladug @bsimpson63

**Comment by spladug** [comment]
lgtm! :fish: very cool

**Comment by andytuba** [comment]
This sounds worth a full-fledged post on /r/changelog and /r/redditdev if it'll be available to third-party apps too.

**Comment by spladug** [comment]
Agree re: redditdev, but not changelog as that should be just for human-facing changes.

**Comment by bsimpson63** [comment]
🐟

**Pull request merged**
