### PR TITLE
Allow the API to specify location for happening_now

### PR DESCRIPTION
**Pull request by markspolakovs**
My first reddit patch, not sure if I did this right 😁

### CODE REVIEW

**Comment by 13steinj** [comment]
The Reddit repositories are considered archived, and potentially the plugin ones as well.

**Comment by spladug** [comment]
Hi! Thanks for your contribution! I'm curious what your use case for this would be? I've added a listing of all featured threads over in #162 which might be related.

**Comment by markspolakovs** [comment]
Hey @spladug, it's basically what you implemented over at #162, so you can probably close this in favour of that one when it gets merged

**Comment by spladug** [comment]
Will do, thanks!

**Comment by markspolakovs** [comment]
Implemented in #162, closing.

**Pull request closed without merging**
