### PR TITLE
Flip around and make stricter subreddit visibility check

### PR DESCRIPTION
**Pull request by spladug**
This was allowing employee-only and gold-only subreddits to show and is
brittle against future expansion.

:eyeglasses: @andytuba @umbrae

### CODE REVIEW

**Comment by andytuba** [comment]
I also see [`if not item.discoverable`](https://github.com/reddit/reddit-public/blob/5f7e090dda478758af2085302db5ee1aa9e05dbc/r2/r2/controllers/listingcontroller.py#L1618), would that be easily available from here?

**Comment by spladug** [comment]
Good point. I've added that as well.

:haircut_man:

**Comment by andytuba** [comment]
looks good to me, but haven't QA'd yet

**Comment by spladug** [comment]
I checked both non-public subreddits and non-r/all subreddits on staging.

**Comment by andytuba** [comment]
Checked a quarantined and an employee-only sub too

https://www.reddit.com/live/y4lxparn27f8   

:fish:

**Comment by spladug** [comment]
a7cde1cf917c4118c4cb114c73a92f272e439816

**Pull request closed without merging**
