### PR TITLE
og:image: Replace smiling snoo with reddit live logo.

### PR DESCRIPTION
**Pull request by spladug**
Embeds for a tragic event with a smiling snoo look quite jarring.

I chose 600px wide because the opengraph docs say: "If your image is smaller than 600 x 315 px, it will still display in the link page post, but the size will be much smaller." and show

the image is small and off to the side of the embed

rather than taking over the whole embed like

huge picture at the top of the embed

which doesn't seem necessary for a logo that's not about the actual content.

I've tested that the `og` tags are updated in our rendered markup, but I've not tested this with Facebook itself. Is there a good way to try that other than rolling into prod?

:eyeglasses: @umbrae @xiongchiamiov

### CODE REVIEW

**Comment by umbrae** [comment]
There's not a great way to test it, but you can use the OG tester: https://developers.facebook.com/tools/debug/

and shove some markup onto a page you host to test it.

**Comment by umbrae** [comment]
They say "Smaller than", and 600 is not technically < 600, so that may cause you an issue.

**Comment by umbrae** [comment]
Oh, but 135 is definitely smaller than 315, so height wise it is smaller, so you'd probably be fine, although it may look weird.

**Comment by umbrae** [comment]
:fish: on the logic itself, I'll leave it to your taste if it looks weird in testing

**Comment by spladug** [comment]
I've updated with a more-square logo:



:haircut:

**Comment by umbrae** [comment]
:fish: aw yeah

**Comment by xiongchiamiov** [comment]
late :fish:

**Comment by spladug** [comment]
03128480b7403bd46b1e7dc298bac2ed4c66deae

**Pull request closed without merging**
